version: "3.9"

services:
  app:
    build: .  # Build the Django application using the provided Dockerfile
    deploy:
      resources:
        limits:
          memory: 100M
          
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application  # Start Gunicorn
    expose:
      - "8000"  # Expose port 8000 for communication with Nginx
    
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  nginx:
    image: nginx:1.25-alpine  # Use a stable Nginx image
    deploy:
      resources:
        limits:
          memory: 100M
    ports:
      - "80:80"  # Redirect HTTP traffic to HTTPS
      #- "443:443"  # Listen for HTTPS traffic
    volumes:
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d:ro  # Mount Nginx configuration files
      - ./infrastructure/certbot/conf:/etc/letsencrypt  # Mount Let's Encrypt configuration files
      - ./infrastructure/certbot/www:/var/www/certbot  # Mount Let's Encrypt challenge files
    depends_on:
      - app  # Ensure app container starts before Nginx

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./infrastructure/certbot/conf:/etc/letsencrypt
  #     - ./infrastructure/certbot/www:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
