  version: "3.9"

  services:
    app:
      build: .  # Build the Django application using the provided Dockerfile          
      command:  ["./entrypoint.sh", "gunicorn", "--bind", "0.0.0.0:8000", "core.wsgi:application"]  # Start Gunicorn
      expose:
        - "8000"  # Expose port 8000 for communication with Nginx
      
      environment:
        - DEBUG=${DEBUG}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - AWS_REGION=$AWS_REGION
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
  
    caddy:
      image: caddy:2.7.6-alpine  # Use a stable Nginx image
      environment:
        - DOMAIN=${DOMAIN}
        - EMAIL=${EMAIL}

      ports:
        - "80:80"
        - "443:443"

      volumes:
        - ./infrastructure/caddy/Caddyfile:/etc/caddy/Caddyfile

      depends_on:
        - app  # Ensure app container starts before Nginx
