# Generated by Django 5.0 on 2024-01-15 20:51

import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_expense_transaction_income_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(default=None, storage=finances.models.determine_storage, upload_to=finances.models.expense_upload_to),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_file',
            field=models.FileField(default=None, storage=finances.models.determine_storage, upload_to=finances.models.expense_upload_to),
        ),
    ]
