name: Deploy via SSH

on:
  push:
    push:
      branches: [ main ]

    pull_request:
      branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v3
      
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          TARGET: /home/finances/app
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
            docker compose up --build -d 
