name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOY_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub

          # Adiciona a chave pública ao arquivo authorized_keys no servidor
          ssh -i ~/.ssh/id_rsa seu_usuario@seu_servidor "echo '${{ secrets.DEPLOY_PUBLIC_KEY }}' >> ~/.ssh/authorized_keys"

          ssh-keyscan -t rsa seu_servidor >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa seu_usuario@seu_servidor 'cd /caminho/para/sua/aplicacao && docker-compose up -d'
